export function useCountriesCode() {
    const countriesCode = ref([
      { code: 'AD', name: 'أندورا', key: '376' },
      { code: 'AE', name: 'الامارات العربية المتحدة', key: '971' },
      { code: 'AF', name: 'أفغانستان', key: '93' },
      { code: 'AL', name: 'ألبانيا', key: '355' },
      { code: 'AM', name: 'أرمينيا', key: '374' },
      { code: 'AO', name: 'أنجولا', key: '244' },
      { code: 'AQ', name: 'القطب الجنوبي', key: '672' },
      { code: 'AR', name: 'الأرجنتين', key: '54' },
      { code: 'AS', name: 'ساموا الأمريكية', key: '1' },
      { code: 'AT', name: 'النمسا', key: '43' },
      { code: 'AU', name: 'أستراليا', key: '61' },
      { code: 'AW', name: 'آروبا', key: '297' },
      { code: 'AX', name: 'جزر أولان', key: '358' },
      { code: 'AZ', name: 'أذربيجان', key: '994' },
      { code: 'BA', name: 'البوسنة والهرسك', key: '387' },
      { code: 'BB', name: 'بربادوس', key: '1' },
      { code: 'BD', name: 'بنجلاديش', key: '880' },
      { code: 'BE', name: 'بلجيكا', key: '32' },
      { code: 'BF', name: 'بوركينا فاسو', key: '226' },
      { code: 'BG', name: 'بلغاريا', key: '359' },
      { code: 'BH', name: 'البحرين', key: '973' },
      { code: 'BI', name: 'بوروندي', key: '257' },
      { code: 'BJ', name: 'بنين', key: '229' },
      { code: 'BL', name: 'سان بارتيلمي', key: '590' },
      { code: 'BM', name: 'برمودا', key: '1' },
      { code: 'BN', name: 'بروناي', key: '673' },
      { code: 'BO', name: 'بوليفيا', key: '591' },
      { code: 'BQ', name: 'بونير', key: '599' },
      { code: 'BR', name: 'البرازيل', key: '55' },
      { code: 'BT', name: 'بوتان', key: '975' },
      { code: 'BV', name: 'جزيرة بوفيه', key: '47' },
      { code: 'BW', name: 'بتسوانا', key: '267' },
      { code: 'BY', name: 'روسيا البيضاء', key: '375' },
      { code: 'BZ', name: 'بليز', key: '501' },
      { code: 'CA', name: 'كندا', key: '1' },
      { code: 'CC', name: 'جزر كوكوس', key: '61' },
      { code: 'CD', name: 'جمهورية الكونغو الديمقراطية', key: '243' },
      { code: 'CF', name: 'جمهورية افريقيا الوسطى', key: '236' },
      { code: 'CG', name: 'الكونغو - برازافيل', key: '242' },
      { code: 'CH', name: 'سويسرا', key: '41' },
      { code: 'CI', name: 'ساحل العاج', key: '225' },
      { code: 'CK', name: 'جزر كوك', key: '682' },
      { code: 'CL', name: 'شيلي', key: '56' },
      { code: 'CM', name: 'الكاميرون', key: '237' },
      { code: 'CN', name: 'الصين', key: '86' },
      { code: 'CO', name: 'كولومبيا', key: '57' },
      { code: 'CR', name: 'كوستاريكا', key: '506' },
      { code: 'CU', name: 'كوبا', key: '53' },
      { code: 'CV', name: 'الرأس الأخضر', key: '238' },
      { code: 'CW', name: 'كوراساو', key: '599' },
      { code: 'CX', name: 'جزيرة الكريسماس', key: '61' },
      { code: 'CY', name: 'قبرص', key: '357' },
      { code: 'CZ', name: 'جمهورية التشيك', key: '420' },
      { code: 'DE', name: 'ألمانيا', key: '49' },
      { code: 'DJ', name: 'جيبوتي', key: '253' },
      { code: 'DK', name: 'الدانمرك', key: '45' },
      { code: 'DZ', name: 'الجزائر', key: '213' },
      { code: 'EC', name: 'الاكوادور', key: '593' },
      { code: 'EE', name: 'استونيا', key: '372' },
      { code: 'EG', name: 'مصر', key: '20' },
      { code: 'EH', name: 'الصحراء الغربية', key: '212' },
      { code: 'ER', name: 'اريتريا', key: '291' },
      { code: 'ES', name: 'أسبانيا', key: '34' },
      { code: 'ET', name: 'اثيوبيا', key: '251' },
      { code: 'FI', name: 'فنلندا', key: '358' },
      { code: 'FJ', name: 'فيجي', key: '679' },
      { code: 'FK', name: 'جزر فوكلاند', key: '500' },
      { code: 'FM', name: 'ميكرونيزيا', key: '691' },
      { code: 'FO', name: 'جزر فارو', key: '298' },
      { code: 'FR', name: 'فرنسا', key: '33' },
      { code: 'GA', name: 'الجابون', key: '241' },
      { code: 'GB', name: 'المملكة المتحدة', key: '44' },
      { code: 'GD', name: 'جرينادا', key: '1' },
      { code: 'GE', name: 'جورجيا', key: '995' },
      { code: 'GF', name: 'غويانا', key: '594' },
      { code: 'GG', name: 'غيرنزي', key: '44' },
      { code: 'GH', name: 'غانا', key: '233' },
      { code: 'GI', name: 'جبل طارق', key: '350' },
      { code: 'GL', name: 'جرينلاند', key: '299' },
      { code: 'GM', name: 'غامبيا', key: '220' },
      { code: 'GN', name: 'غينيا', key: '224' },
      { code: 'GP', name: 'جوادلوب', key: '590' },
      { code: 'GQ', name: 'غينيا الاستوائية', key: '240' },
      { code: 'GR', name: 'اليونان', key: '30' },
      { code: 'GS', name: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', key: '500' },
      { code: 'GT', name: 'جواتيمالا', key: '502' },
      { code: 'GW', name: 'غينيا بيساو', key: '245' },
      { code: 'GY', name: 'غيانا', key: '595' },
      { code: 'HK', name: 'هونج كونج الصينية', key: '852' },
      { code: 'HM', name: 'جزيرة هيرد وماكدونالد', key: '' },
      { code: 'HN', name: 'هندوراس', key: '504' },
      { code: 'HR', name: 'كرواتيا', key: '385' },
      { code: 'HT', name: 'هايتي', key: '509' },
      { code: 'HU', name: 'المجر', key: '36' },
      { code: 'ID', name: 'اندونيسيا', key: '62' },
      { code: 'IE', name: 'أيرلندا', key: '353' },
      { code: 'IM', name: 'جزيرة مان', key: '44' },
      { code: 'IN', name: 'الهند', key: '91' },
      { code: 'IO', name: 'المحيط الهندي البريطاني', key: '246' },
      { code: 'IQ', name: 'العراق', key: '964' },
      { code: 'IR', name: 'ايران', key: '98' },
      { code: 'IS', name: 'أيسلندا', key: '354' },
      { code: 'IT', name: 'ايطاليا', key: '39' },
      { code: 'JE', name: 'جيرسي', key: '44' },
      { code: 'JM', name: 'جامايكا', key: '1' },
      { code: 'JO', name: 'الأردن', key: '962' },
      { code: 'JP', name: 'اليابان', key: '81' },
      { code: 'KE', name: 'كينيا', key: '254' },
      { code: 'KG', name: 'قرغيزستان', key: '996' },
      { code: 'KH', name: 'كمبوديا', key: '855' },
      { code: 'KI', name: 'كيريباتي', key: '686' },
      { code: 'KM', name: 'جزر القمر', key: '269' },
      { code: 'KN', name: 'سانت كيتس ونيفيس', key: '1' },
      { code: 'KP', name: 'كوريا الشمالية', key: '850' },
      { code: 'KR', name: 'كوريا الجنوبية', key: '82' },
      { code: 'KW', name: 'الكويت', key: '965' },
      { code: 'KY', name: 'جزر الكايمن', key: '345' },
      { code: 'KZ', name: 'كازاخستان', key: '7' },
      { code: 'LA', name: 'لاوس', key: '856' },
      { code: 'LB', name: 'لبنان', key: '961' },
      { code: 'LC', name: 'سانت لوسيا', key: '1' },
      { code: 'LI', name: 'ليختنشتاين', key: '423' },
      { code: 'LK', name: 'سريلانكا', key: '94' },
      { code: 'LR', name: 'ليبيريا', key: '231' },
      { code: 'LS', name: 'ليسوتو', key: '266' },
      { code: 'LT', name: 'ليتوانيا', key: '370' },
      { code: 'LU', name: 'لوكسمبورج', key: '352' },
      { code: 'LV', name: 'لاتفيا', key: '371' },
      { code: 'LY', name: 'ليبيا', key: '218' },
      { code: 'MA', name: 'المغرب', key: '212' },
      { code: 'MC', name: 'موناكو', key: '377' },
      { code: 'MD', name: 'مولدافيا', key: '373' },
      { code: 'ME', name: 'الجبل الأسود', key: '382' },
      { code: 'MF', name: 'سانت مارتين', key: '590' },
      { code: 'MG', name: 'مدغشقر', key: '261' },
      { code: 'MH', name: 'جزر المارشال', key: '692' },
      { code: 'MK', name: 'مقدونيا', key: '389' },
      { code: 'ML', name: 'مالي', key: '223' },
      { code: 'MM', name: 'ميانمار', key: '95' },
      { code: 'MN', name: 'منغوليا', key: '976' },
      { code: 'MO', name: 'ماكاو الصينية', key: '853' },
      { code: 'MP', name: 'جزر ماريانا الشمالية', key: '1' },
      { code: 'MQ', name: 'مارتينيك', key: '596' },
      { code: 'MR', name: 'موريتانيا', key: '222' },
      { code: 'MS', name: 'مونتسرات', key: '1' },
      { code: 'MT', name: 'مالطا', key: '356' },
      { code: 'MU', name: 'موريشيوس', key: '230' },
      { code: 'MV', name: 'جزر الملديف', key: '960' },
      { code: 'MW', name: 'ملاوي', key: '265' },
      { code: 'MX', name: 'المكسيك', key: '52' },
      { code: 'MY', name: 'ماليزيا', key: '60' },
      { code: 'MZ', name: 'موزمبيق', key: '258' },
      { code: 'NA', name: 'ناميبيا', key: '264' },
      { code: 'NC', name: 'كاليدونيا الجديدة', key: '687' },
      { code: 'NE', name: 'النيجر', key: '227' },
      { code: 'NF', name: 'جزيرة نورفوك', key: '672' },
      { code: 'NG', name: 'نيجيريا', key: '234' },
      { code: 'NI', name: 'نيكاراجوا', key: '505' },
      { code: 'NL', name: 'هولندا', key: '31' },
      { code: 'NO', name: 'النرويج', key: '47' },
      { code: 'NP', name: 'نيبال', key: '977' },
      { code: 'NR', name: 'نورو', key: '674' },
      { code: 'NU', name: 'نيوي', key: '683' },
      { code: 'NZ', name: 'نيوزيلاندا', key: '64' },
      { code: 'OM', name: 'عمان', key: '968' },
      { code: 'PA', name: 'بنما', key: '507' },
      { code: 'PE', name: 'بيرو', key: '51' },
      { code: 'PF', name: 'بولينيزيا الفرنسية', key: '689' },
      { code: 'PG', name: 'بابوا غينيا الجديدة', key: '675' },
      { code: 'PH', name: 'الفيلبين', key: '63' },
      { code: 'PK', name: 'باكستان', key: '92' },
      { code: 'PL', name: 'بولندا', key: '48' },
      { code: 'PM', name: 'سانت بيير وميكولون', key: '508' },
      { code: 'PN', name: 'بتكايرن', key: '872' },
      { code: 'PR', name: 'بورتوريكو', key: '1' },
      { code: 'PS', name: 'فلسطين', key: '970' },
      { code: 'PT', name: 'البرتغال', key: '351' },
      { code: 'PW', name: 'بالاو', key: '680' },
      { code: 'PY', name: 'باراجواي', key: '595' },
      { code: 'QA', name: 'قطر', key: '974' },
      { code: 'RE', name: 'روينيون', key: '262' },
      { code: 'RO', name: 'رومانيا', key: '40' },
      { code: 'RS', name: 'صربيا', key: '381' },
      { code: 'RU', name: 'روسيا', key: '7' },
      { code: 'RW', name: 'رواندا', key: '250' },
      { code: 'SA', name: 'المملكة العربية السعودية', key: '966' },
      { code: 'SB', name: 'جزر سليمان', key: '677' },
      { code: 'SC', name: 'سيشل', key: '248' },
      { code: 'SD', name: 'السودان', key: '249' },
      { code: 'SE', name: 'السويد', key: '46' },
      { code: 'SG', name: 'سنغافورة', key: '65' },
      { code: 'SH', name: 'سانت هيلنا', key: '290' },
      { code: 'SI', name: 'سلوفينيا', key: '386' },
      { code: 'SJ', name: 'سفالبارد وجان مايان', key: '47' },
      { code: 'SK', name: 'سلوفاكيا', key: '421' },
      { code: 'SL', name: 'سيراليون', key: '232' },
      { code: 'SM', name: 'سان مارينو', key: '378' },
      { code: 'SN', name: 'السنغال', key: '221' },
      { code: 'SO', name: 'الصومال', key: '252' },
      { code: 'SR', name: 'سورينام', key: '597' },
      { code: 'SS', name: 'جنوب السودان', key: '211' },
      { code: 'ST', name: 'ساو تومي وبرينسيبي', key: '239' },
      { code: 'SV', name: 'السلفادور', key: '503' },
      { code: 'SX', name: 'سينت مارتن', key: '1' },
      { code: 'SY', name: 'سوريا', key: '963' },
      { code: 'SZ', name: 'سوازيلاند', key: '268' },
      { code: 'TC', name: 'جزر الترك وجايكوس', key: '1' },
      { code: 'TD', name: 'تشاد', key: '235' },
      { code: 'TF', name: 'المقاطعات الجنوبية الفرنسية', key: '262' },
      { code: 'TG', name: 'توجو', key: '228' },
      { code: 'TH', name: 'تايلند', key: '66' },
      { code: 'TJ', name: 'طاجكستان', key: '992' },
      { code: 'TK', name: 'توكيلو', key: '690' },
      { code: 'TL', name: 'تيمور الشرقية', key: '670' },
      { code: 'TM', name: 'تركمانستان', key: '993' },
      { code: 'TN', name: 'تونس', key: '216' },
      { code: 'TO', name: 'تونجا', key: '676' },
      { code: 'TR', name: 'تركيا', key: '90' },
      { code: 'TT', name: 'ترينيداد وتوباغو', key: '1' },
      { code: 'TV', name: 'توفالو', key: '688' },
      { code: 'TW', name: 'تايوان', key: '886' },
      { code: 'TZ', name: 'تانزانيا', key: '255' },
      { code: 'UA', name: 'أوكرانيا', key: '380' },
      { code: 'UG', name: 'أوغندا', key: '256' },
      { code: 'US', name: 'الولايات المتحدة الأمريكية', key: '1' },
      { code: 'UY', name: 'أورجواي', key: '598' },
      { code: 'UZ', name: 'أوزبكستان', key: '998' },
      { code: 'VA', name: 'الفاتيكان', key: '379' },
      { code: 'VC', name: 'سانت فنسنت وغرنادين', key: '1' },
      { code: 'VE', name: 'فنزويلا', key: '58' },
      { code: 'VG', name: 'جزر فرجين البريطانية', key: '1' },
      { code: 'VI', name: 'جزر فرجين الأمريكية', key: '1' },
      { code: 'VN', name: 'فيتنام', key: '84' },
      { code: 'VU', name: 'فانواتو', key: '678' },
      { code: 'WF', name: 'جزر والس وفوتونا', key: '681' },
      { code: 'WS', name: 'ساموا', key: '685' },
      { code: 'XK', name: 'كوسوفو', key: '383' },
      { code: 'YE', name: 'اليمن', key: '967' },
      { code: 'YT', name: 'مايوت', key: '262' },
      { code: 'ZA', name: 'جمهورية جنوب افريقيا', key: '27' },
      { code: 'ZM', name: 'زامبيا', key: '260' },
      { code: 'ZW', name: 'زيمبابوي', key: '263' },
    ]);
  
    return {
      countriesCode,
    };
  }
  